extract_outline_from_transcription:
  description: >
    📋 EXTRAÇÃO E ESTRUTURAÇÃO DE OUTLINE TÉCNICO

    Analisar a transcrição do vídeo fornecida e executar um processo estruturado de extração de conhecimento:

    ETAPA 1 - ANÁLISE INICIAL:
    - Ler completamente a transcrição para compreender o contexto geral
    - Identificar o tema principal e sub-temas técnicos discutidos
    - Mapear a progressão lógica da conversa
    - Detectar momentos de deep-dive técnico vs overview conceitual

    ETAPA 2 - FILTRAGEM E LIMPEZA:
    - Remover ruídos conversacionais (uhm, ah, repetições, interjeições)
    - Eliminar tangentes não-técnicas ou irrelevantes
    - Identificar e preservar insights técnicos valiosos mesmo em conversas casuais
    - Detectar correções ou refinamentos feitos durante a conversa

    ETAPA 3 - ESTRUTURAÇÃO HIERÁRQUICA:
    - Criar outline com títulos acompanhados de emojis contextuais
    - Estabelecer hierarquia clara: conceitos principais (H1) → sub-conceitos (H2) → detalhes (H3)
    - Marcar tópicos que demandam exemplos de código
    - Identificar conceitos que precisam de contexto adicional
    - Categorizar por nível de complexidade (🟢 Básico, 🟡 Intermediário, 🔴 Avançado)

    ENTRADA:
    <transcription>
      {transcription}
    </transcription>

  expected_output: >
    Outline técnico estruturado em markdown seguindo este formato obrigatório:

    # 🎯 [Título Principal da Documentação]

    ## 📋 Resumo Executivo
    [Resumo de 2-3 linhas do conteúdo técnico]

    ## 🏗️ Estrutura do Conteúdo

    ### 🔧 [Tópico Principal 1] (🟢/🟡/🔴)
    - [Subtópico 1.1]
    - [Subtópico 1.2] *(necessita exemplo de código)*

    ### ⚙️ [Tópico Principal 2] (🟢/🟡/🔴)
    - [Subtópico 2.1] *(contexto adicional necessário)*
    - [Subtópico 2.2]

    ## 💡 Insights Identificados
    - [Lista de insights técnicos extraídos]

    ## 🔍 Gaps de Informação
    - [Pontos que precisam ser expandidos pelo próximo agente]

  agent: technical_content_analyst


expand_and_validate_technical_details:
  description: >
    🏗️ EXPANSÃO E VALIDAÇÃO ARQUITETURAL PROFUNDA

    Transformar o outline estruturado em documentação técnica robusta através de processo sistemático de enriquecimento:

    FASE 1 - VALIDAÇÃO DO OUTLINE:
    - Revisar a estrutura proposta contra a transcrição original
    - Identificar lacunas técnicas ou imprecisões conceituais
    - Validar a hierarquia e categorização de complexidade
    - Detectar oportunidades de melhoria na organização

    FASE 2 - EXPANSÃO TÉCNICA DETALHADA:
    Para cada tópico do outline, desenvolver:
    - **Contexto Arquitetural**: Por que esta solução? Qual problema resolve?
    - **Implementação Técnica**: Como funciona internamente?
    - **Exemplos de Código**: Snippets práticos e funcionais com explicações linha por linha
    - **Trade-offs**: Prós, contras, limitações e alternativas
    - **Decisões de Design**: Justificativas arquiteturais baseadas em requisitos
    - **Padrões Aplicados**: Design patterns, architectural patterns utilizados
    - **Performance e Escalabilidade**: Considerações de throughput, latência, recursos
    - **Evolução Histórica**: Como chegamos a esta solução (se aplicável)

    FASE 3 - ENRIQUECIMENTO CONTEXTUAL:
    - Adicionar referências a documentação oficial, RFCs, papers relevantes
    - Incluir métricas, benchmarks ou dados de performance quando pertinente
    - Conectar conceitos com o ecossistema tecnológico maior
    - Identificar anti-padrões e armadilhas comuns

    FASE 4 - REFINAMENTO DE CONTEÚDO:
    - Eliminar inconsistências e redundâncias da transcrição original
    - Corrigir erros conceituais ou imprecisões técnicas
    - Reorganizar informação para fluxo lógico otimizado
    - Garantir precisão terminológica e técnica

    ENTRADA PRIMÁRIA:
    <transcription>
      {transcription}
    </transcription>

  expected_output: >
    Documentação técnica expandida seguindo estrutura rigorosa:

    # 🎯 [Título com Foco na Solução/Conceito Principal]

    ## 📋 Overview Executivo
    [Resumo técnico de 3-4 linhas com context, solution, impact]

    ## 🎪 Contexto e Motivação
    [Por que este tópico é importante? Qual problema resolve?]

    ## 🏗️ [Seção Principal 1] (🟢/🟡/🔴)

    ### 💡 Conceito Fundamental
    [Explicação conceitual clara antes de mergulhar em detalhes]

    ### 🔧 Implementação Técnica
    [Como funciona na prática]

    ```[linguagem]
    // Exemplo de código com comentários explicativos
    [código funcionais e práticos]
    ```

    ### ⚖️ Trade-offs e Considerações
    **Prós:**
    - [Lista de vantagens]

    **Contras:**
    - [Lista de limitações]

    **Quando usar:**
    - [Cenários apropriados]

    ### 🔍 Detalhes Arquiteturais
    [Deep dive em decisões de design, padrões aplicados]

    ## 📊 Performance e Escalabilidade
    [Métricas, benchmarks, considerações de escala quando aplicável]

    ## 🚨 Armadilhas Comuns
    [Anti-padrões e erros frequentes a evitar]

    ## 🔗 Referências e Recursos
    [Links para documentação oficial, papers, tools]

    ## 🚀 Próximos Passos
    [O que aprender/explorar em seguida]

  agent: senior_software_architect


refine_for_clarity_and_structure:
  description: >
    ✍️ REFINAMENTO EDITORIAL E ESTRUTURAL PARA DEVELOPER EXPERIENCE

    Transformar a documentação técnica expandida em material publication-ready através de processo editorial rigoroso:

    ETAPA 1 - ANÁLISE ESTRUTURAL:
    - Avaliar fluxo narrativo e progressão lógica
    - Identificar gaps na progressão do conhecimento
    - Verificar consistência na aplicação de padrões visuais
    - Analisar cognitive load e pontos de possível sobrecarga

    ETAPA 2 - APLICAÇÃO DE PADRÕES OBRIGATÓRIOS:

    **ESTRUTURA VISUAL MANDATÓRIA:**
    - ✅ Títulos e subtítulos com emojis contextuais e consistentes
    - ✅ Introdução com problema/contexto antes de soluções
    - ✅ Progressão conceitual → implementação → exemplos → aplicação
    - ✅ Code blocks sempre precedidos de contexto explicativo
    - ✅ Seções padronizadas: "💡 Pontos-chave", "⚠️ Armadilhas", "🚀 Próximos Passos"

    **CALL-OUTS VISUAIS OBRIGATÓRIOS:**
    - 💡 **Dica:** Insights valiosos e best practices
    - ⚠️ **Atenção:** Avisos sobre armadilhas e limitações
    - 🔍 **Aprofundamento:** Links para recursos avançados
    - 📝 **Exemplo:** Casos práticos e aplicações reais
    - 🎯 **Resumo:** Consolidação de conceitos-chave

    ETAPA 3 - OTIMIZAÇÃO DE LINGUAGEM:
    - Converter jargão técnico em linguagem acessível (mas precisa)
    - Implementar storytelling técnico com analogias eficazes
    - Garantir tom conversacional mas profissional
    - Eliminar ambiguidades e termos vagos
    - Padronizar terminologia ao longo do documento

    ETAPA 4 - OTIMIZAÇÃO PEDAGÓGICA:
    - Quebrar informação complexa em chunks digestíveis
    - Adicionar contexto suficiente para cada conceito
    - Garantir que código tenha propósito claro e comentários úteis
    - Implementar técnicas de cognitive load reduction
    - Validar que progressão atende diferentes learning styles

    ETAPA 5 - EXPERIÊNCIA DE LEITURA:
    - Otimizar para skimming (headers, bullet points, highlights)
    - Garantir que deep-diving seja recompensador
    - Facilitar copy-paste de código com contexto preservado
    - Adicionar navegação interna e referências cruzadas

  expected_output: >
    Documentação refinada e publication-ready seguindo template rigoroso:

    # 🎯 [Título Claro e Descritivo]

    > 📖 **Tempo de leitura:** ~X minutos | **Nível:** 🟢 Básico / 🟡 Intermediário / 🔴 Avançado

    ## 📋 TL;DR
    [Resumo executivo em 2-3 bullet points para readers com pressa]

    ## 🎪 Contexto e Problema
    [Setup do problema de forma envolvente, contextualizando a necessidade]

    ## 🏗️ [Seção Principal]

    ### 💡 Conceito Central
    [Explicação conceitual clara com analogias quando útil]

    ### 🔧 Como Implementar
    [Passos práticos e implementação]

    ```javascript
    // Contexto: Este exemplo demonstra [propósito específico]
    function exemploClaro() {
        // Comentário explicativo útil
        return "código funcional com contexto";
    }
    ```

    💡 **Dica:** [Insight valioso relacionado ao código acima]

    ### ⚖️ Quando Usar vs Não Usar

    **✅ Use quando:**
    - Cenário específico A
    - Requisito específico B

    **❌ Evite quando:**
    - Limitação específica C
    - Anti-pattern específico D

    ## 💡 Pontos-chave
    - [Takeaway principal 1]
    - [Takeaway principal 2]
    - [Takeaway principal 3]

    ## ⚠️ Armadilhas Comuns
    - [Erro comum 1 e como evitar]
    - [Erro comum 2 e como evitar]

    ## 🔗 Recursos Adicionais
    - [Link 1 com descrição clara do que encontrar]
    - [Link 2 com contexto de quando usar]

    ## 🚀 Próximos Passos
    [Sugestões claras de como expandir o conhecimento ou aplicar na prática]

  agent: technical_writer


perform_peer_review_and_feedback:
  description: >
    🔍 PEER REVIEW ABRANGENTE E VALIDAÇÃO MULTI-DIMENSIONAL
    
    Executar processo rigoroso de revisão através de múltiplas perspectivas críticas para garantir excelência final:
    
    DIMENSÃO 1 - VALIDAÇÃO TÉCNICA PROFUNDA:
    
    **Accuracy Assessment:**
    - Verificar precisão de todos os conceitos técnicos apresentados
    - Validar viabilidade e funcionalidade de todos os exemplos de código
    - Confirmar alinhamento com best practices atuais da indústria
    - Identificar potential security concerns ou anti-patterns
    - Checar referências e links para recursos externos
    
    **Completude Técnica:**
    - Avaliar se informações críticas estão missing
    - Verificar se edge cases importantes foram considerados
    - Validar se contexto arquitetural é suficiente
    - Confirmar que trade-offs estão adequadamente representados
    
    DIMENSÃO 2 - VALIDAÇÃO PEDAGÓGICA E UX:
    
    **Clarity Assessment:**
    - Testar compreensibilidade para diferentes níveis técnicos
    - Identificar pontos de possível confusão ou ambiguidade
    - Validar eficácia das analogias e explicações conceituais
    - Verificar se progressão de conhecimento é lógica e incremental
    
    **Learning Experience:**
    - Avaliar se exemplos são motivadores e práticos
    - Verificar se "aha moments" estão bem posicionados
    - Confirmar que cognitive load está bem distribuído
    - Validar se call-to-actions são inspiradores e acionáveis
    
    DIMENSÃO 3 - VALIDAÇÃO ESTRUTURAL E CONSISTÊNCIA:
    
    **Pattern Compliance:**
    - Verificar aplicação consistente de emojis e formatação
    - Validar adherência aos templates estabelecidos
    - Confirmar qualidade e relevância dos call-outs visuais
    - Checar hierarquia de headers e navegabilidade
    
    **Publication Readiness:**
    - Avaliar spelling, grammar e fluência da linguagem
    - Verificar links funcionais e referências precisas
    - Confirmar que metadados estão completos
    - Validar otimização para diferentes modos de consumo (skimming vs deep-dive)
    
    DIMENSÃO 4 - FEEDBACK E REFINAMENTO:
    - Identificar oportunidades específicas de melhoria
    - Sugerir adições que aumentariam valor para o leitor
    - Propor simplificações onde complexity não agrega valor
    - Recomendar ajustes para melhor developer experience

  expected_output: >
    Documentação final revisada e validada, incluindo relatório de revisão:

    [DOCUMENTAÇÃO REFINADA COM TODAS AS CORREÇÕES APLICADAS]
    
    ---
    
    ## 📊 RELATÓRIO DE PEER REVIEW
    
    ### ✅ Validações Confirmadas
    - **Precisão Técnica:** [Status e observações]
    - **Completude:** [Status e observações]
    - **Clareza Pedagógica:** [Status e observações]
    - **Consistência Estrutural:** [Status e observações]
    
    ### 🎯 Principais Melhorias Implementadas
    1. [Melhoria específica 1]
    2. [Melhoria específica 2]
    3. [Melhoria específica 3]
    
    ### 💡 Pontos Fortes Identificados
    - [Aspecto particularmente bem executado 1]
    - [Aspecto particularmente bem executado 2]
    
    ### 🎯 Público-Alvo Validado
    **Ideal para:** [Descrição do público que mais se beneficiará]
    **Pré-requisitos:** [Conhecimentos necessários para aproveitamento máximo]
    **Valor Agregado:** [Principal takeaway e aplicação prática]
    
    ### 📈 Score de Qualidade
    - **Técnica:** ⭐⭐⭐⭐⭐
    - **Pedagógica:** ⭐⭐⭐⭐⭐  
    - **Estrutural:** ⭐⭐⭐⭐⭐
    - **Overall:** ⭐⭐⭐⭐⭐

  agent: peer_reviewer


publish_and_distribute_documentation:
  description: >
    📚 PUBLICAÇÃO E DISTRIBUIÇÃO FINAL DA DOCUMENTAÇÃO
    
    Executar processo final de publicação, garantindo máxima qualidade e experiência do usuário na documentação entregue:
    
    FASE 1 - PREPARAÇÃO PARA PUBLICAÇÃO:
    
    **Formatting Final:**
    - Aplicar markdown limpo e bem estruturado sem inconsistências
    - Garantir hierarquia de headers totalmente consistente (H1 > H2 > H3)
    - Verificar syntax highlighting correto em todos os code blocks
    - Confirmar aplicação uniforme e contextual de emojis
    - Validar links internos e externos funcionais
    
    **Metadados e Organização:**
    - Adicionar título principal claro e SEO-friendly
    - Incluir abstract/sumário executivo quando apropriado
    - Estabelecer tags de categorização técnica
    - Calcular e incluir estimativa de tempo de leitura
    - Indicar claramente nível de dificuldade (🟢🟡🔴)
    - Adicionar data de criação e versioning information
    
    FASE 2 - CONTROLE DE QUALIDADE FINAL:
    
    **Technical Validation:**
    - Executar spell-check e grammar validation completos
    - Testar funcionamento de todos os code examples
    - Verificar accuracy de todas as referências técnicas
    - Confirmar links externos ativos e relevantes
    - Validar sintaxe markdown em diferentes renderers
    
    **User Experience Optimization:**
    - Otimizar para diferentes modos de consumo (mobile, desktop)
    - Garantir experiência fluida tanto para skimming quanto deep-reading
    - Facilitar copy-paste de código mantendo contexto
    - Adicionar navigation aids (table of contents se necessário)
    - Implementar call-to-actions inspiradores e acionáveis
    
    FASE 3 - PUBLICAÇÃO ESTRUTURADA:
    
    **Distribution Preparation:**
    - Formatar para plataforma de destino (Markdown padrão)
    - Garantir compatibilidade com sistemas de versionamento
    - Preparar documentação para fácil discovery e indexing
    - Adicionar metadata para tracking e analytics
    - Incluir canais de feedback e contribution guidelines
    
    **Final Polish:**
    - Revisão final de consistência visual e estrutural
    - Verificação de compliance com todos os padrões estabelecidos
    - Validação de que developer experience é otimizada
    - Confirmação de que documentação está truly publication-ready

  expected_output: >
    Documentação final publication-ready com formatação perfeita:

    # 🎯 [Título Principal Otimizado]
    
    > 📖 **Tempo de leitura:** ~X minutos | **Nível:** 🟢 Básico / 🟡 Intermediário / 🔴 Avançado  
    > 🏷️ **Tags:** [tag1, tag2, tag3] | **Versão:** 1.0 | **Atualizado:** [data]
    
    ## 📋 TL;DR
    [Resumo executivo ultra-conciso em 2-3 bullet points]
    
    ## 🎪 Contexto e Problema
    [Introdução envolvente que contextualiza a necessidade]
    
    [CONTEÚDO PRINCIPAL COMPLETAMENTE FORMATADO E POLIDO]
    
    ---
    
    ## 📊 Metadados da Documentação
    
    **Informações Técnicas:**
    - **Complexidade:** [Nível detalhado]
    - **Pré-requisitos:** [Lista específica]
    - **Tecnologias:** [Stack relevante]
    - **Casos de Uso:** [Scenarios primários]
    
    **Qualidade Assegurada:**
    - ✅ Code examples testados e funcionais
    - ✅ Links verificados e atuais
    - ✅ Spelling e grammar validados
    - ✅ Formatação markdown otimizada
    - ✅ SEO e discoverability otimizados
    
    **Suporte e Feedback:**
    - 💬 **Feedback:** [canal para feedback]
    - 🤝 **Contribuições:** [processo de contribuição]
    - 📅 **Próxima revisão:** [timeline de updates]

  output_file: >
    {output_path}/{output_filename}

  agent: documentation_publisher
